#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoenix.Droid.Resource", IsApplication=true)]

namespace Phoenix.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020003
			public const int btn_next = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btn_start = 2130837508;
			
			// aapt resource value: 0x7F020000
			public const int Buttons = 2130837504;
			
			// aapt resource value: 0x7F020005
			public const int carousel1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int carousel2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int carousel3 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int carousel4 = 2130837512;
			
			// aapt resource value: 0x7F020001
			public const int Checkbox_Checked = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Checkbox_Unchecked = 2130837506;
			
			// aapt resource value: 0x7F020009
			public const int comming_soon = 2130837513;
			
			// aapt resource value: 0x7F020010
			public const int icon_account = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int icon_bell = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int icon_blog = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int icon_cart = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int icon_cdb = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int icon_feedback = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int icon_hospital = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int icon_meeting = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int icon_membercard = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int icon_message = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int icon_mydoctor = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int icon_qrcode = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int icon_register = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int icon_setting = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int icon_success = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int icon_video = 2130837535;
			
			// aapt resource value: 0x7F02000A
			public const int ic_act_code = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int ic_act_home = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int ic_act_idea = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int ic_act_more = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ic_act_notify = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int ic_launcher = 2130837519;
			
			// aapt resource value: 0x7F020020
			public const int launcher_foreground = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int splash_screen = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int unknown = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int xamarin_logo = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int bottomtab_navarea = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int bottomtab_tabbar = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int bottomtab_tabbar_container = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sliding_tabs = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int toolbar = 2130903044;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int BottomTabLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Tabbar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Toolbar = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050005
			public const int icon = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int icon_round = 2131034118;
			
			// aapt resource value: 0x7F050000
			public const int ic_act_account = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_act_bell = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_act_code = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_act_home = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ic_launcher = 2131034116;
			
			// aapt resource value: 0x7F050007
			public const int launcher_foreground = 2131034119;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int SplashTheme_Splash = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F070000
			public const int file_paths = 2131165184;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
